var colorLookup = {
  "ribosomal protein S10": "grey",
  "Histidyl tRNA synthetase": "#7fa83b",
  "Phenylalanyl tRNA synthetase alpha": "#7fa83b",
  "Preprotein translocase subunit SecY": "#7fa83b",
  "Valyl tRNA synthetase": "#7fa83b",
  "gyrA": "#7fa83b",
  "leucyl tRNA synthetase": "#7fa83b",
  "recA": "#7fa83b",
  "ribosomal protein L1": "grey",
  "ribosomal protein L11": "grey",
  "ribosomal protein L13": "grey",
  "ribosomal protein L14": "grey",
  "ribosomal protein L15": "grey",
  "ribosomal protein L16 L10E": "#7fa83b",
  "ribosomal protein L18": "grey",
  "ribosomal protein L2": "grey",
  "ribosomal protein L22": "grey",
  "ribosomal protein L3": "grey",
  "ribosomal protein L4": "grey",
  "ribosomal protein L5": "grey",
  "ribosomal protein L6P L9E": "#7fa83b",
  "ribosomal protein S11": "grey",
  "ribosomal protein S13": "grey",
  "ribosomal protein S17": "grey",
  "ribosomal protein S19": "grey",
  "ribosomal protein S2": "grey",
  "ribosomal protein S3": "grey",
  "ribosomal protein S4": "grey",
  "ribosomal protein S7": "grey",
  "ribosomal protein S8": "grey",
  "ribosomal protein S9": "grey",
  "aspartyl tRNA synthetase": "#7fa83b",
  "arginyl tRNA synthetase": "#7fa83b",
  "alanyl tRNA synthetase": "#7fa83b",
  "ribosomal protein L10": "grey",
  "ribosomal protein L17": "grey",
  "ribosomal protein L19": "grey",
  "ribosomal protein L20": "grey",
  "ribosomal protein L21": "grey",
  "ribosomal protein L23": "grey",
  "ribosomal protein L24": "grey",
  "ribosomal protein L27": "grey",
  "ribosomal protein L29": "grey",
  "ribosomal protein L30": "grey",
  "ribosomal protein S5": "grey",
  "ribosomal protein S6": "grey",
  "ribosomal protein S12": "grey",
  "ribosomal protein S15": "grey",
  "ribosomal protein S16": "grey",
  "ribosomal protein S18": "grey",
  "ribosomal protein S20": "grey",
  "ribosomal protein L16": "grey",
  "ribosomal protein L25": "grey",
  "ribosomal protein L28": "grey",
  "ribosomal protein L31": "grey",
  "ribosomal protein L32": "grey",
  "ribosomal protein L33": "grey",
  "ribosomal protein L34": "grey",
  "ribosomal protein L35": "grey",
  "ribosomal protein L6": "grey",
  "ribosomal protein L7\/L12": "grey",
  "ribosomal protein L9": "grey",
  "ribosomal protein S1": "grey",
  "ribosomal protein S14": "grey",
  "ribosomal protein S22": "grey",
  "ribosomal protein S23": "grey",
  "ribosomal protein S24": "grey",
  "AMP salvage pathway": "#5377f5",
  "AMP_salvage_Pathway_AMP phosphorylase": "#139a9c",
  "AMP_salvage_Pathway_Ribose-1,5-bisphosphate isomerase": "#139a9c",
  "AMP_salvage_pathway_RuBisCO": "#139a9c",
  "EMP_phosphoglucomutase": "#7c8bd6",
  "EMP_glucose-6-P\/mannose-6-P_isomerase_(PGI)": "#7c8bd6",
  "EMP_pyruvate_kinase": "#7c8bd6",
  "pyruvate_phosphate_dikinase\/PEP_synthase": "#acc8f2",
  "EMP_Phosphofructokinase": "#7c8bd6",
  "EMP_fructose bisphosphate aldolase": "#7c8bd6",
  "EMP_triose phosphate isomerase": "#7c8bd6",
  "EMP_glyceraldehyde-3-phosphate dehydrogenase": "#7c8bd6",
  "EMP_phosphoglycerate_kinase": "#7c8bd6",
  "EMP_phosphoglyceromutase_(PGM)": "#7c8bd6",
  "EMP_enolase": "#7c8bd6",
  "PP_glucose-6-P-1-dehydrogenase": "#dec8e6",
  "PP_6-phosphogluconate_dehydrogenase": "#dec8e6",
  "PP_ribose-5-P_isomerase": "#856491",
  "PP_ribulose-P_3-epimerase": "#856491",
  "PP_transketolase": "#856491",
  "PP_transaldolase": "#856491",
  "Redox_Ferredoxins": "#a8e3d5",
  "Pyrophosphatase_non-pumping": "#e69567",
  "Pyrophosphatase_pumping": "#e69567",
  "Pyruvate_pyruvate_formate_lyase": "#27ce79",
  "Pyruvate_PFOR_alpha": "#27ce79",
  "Pyruvate_PFOR_beta": "#27ce79",
  "Redox_NiFe_Hydrogenase": "#779bbd",
  "Translation_tRNA_synthetases": "#9dd99c",
  "ATP synthase_Complex_V": "#e69567",
  "Complex_I_NADH_Dehydrogenase": "#e69567",
  "Cellulose Degradation_3.2.1.21_3.2.1.4_3.2.1.91": "#f7d49c",
  "Acetate Production (ACK-PTA) ": "#ffc2c2",
  "Acetate Production *alternate*": "#ffc2c2",
  "DNA gyrase subunit A": "#7fa83b",
  "DNA gyrase subunit B": "#7fa83b",
  "Aldehyde_DH_Ethanol_Production": "#ffc2c2",
  "Alcohol_DH_Ethanol_Production": "#ffc2c2",
  "Fe-Hydrogenase": "#779bbd",
  "Lactate_Dehydrogenase_ARCH": "#ffc2c2",
  "Cytochrome_c_oxidase_subunit II_Complex_IV": "#e69567",
  "Pyruvate_dehydrogenase": "#27ce79",
  "Nitrogen_Assimilation_pathways": "#383233",
  "NitrogenFix_NifHDK": "#d46169",
  "Pyruvate_Malic_Enzyme": "#27ce79",
  "Cas proteins": "#ed1515",
  "Cell_surface_Fibronectin": "#b07979",
  "Cell_surface_PKD-domain containing": "#b07979",
  "Cell_surface_teichoic_acid": "#b07979",
  "EMP_glucokinase": "#7c8bd6",
  "Lipopolysaccharide_biosynthesis": "#d4ff00",
  "Pili_PilT_Twitching_NTPase": "#04ca88",
  "Pili_pilB_traffic_NTPase": "#04ca88",
  "Pili_pilD_leader_peptidase": "#04ca88",
  "Pili_Pilins": "#04ca88",
  "Pili_pilM_membrane_protein": "#04ca88",
  "Ggkbase_Pur_1_PurF_phosphoribosylamidotransferase": "#fb5746",
  "Pur_10_IMP_cyclohydrolase": "#fb5746",
  "Pur_10_PurA_adenylosuccinate_synthase": "#fb5746",
  "Pur_11_PurB_adenylosuccinate_lyase": "#fb5746",
  "Pur_12_IMP_dehydrogenase": "#fb5746",
  "Pur_13_GMP_synthase": "#fb5746",
  "Pur_14_xanthine_phosphoribosyltransferase": "#fb5746",
  "Pur_2_PurD_Phosphoribosylglycinamide_synthase": "#fb5746",
  "Pur_3_purN_purT_Phosphoribosylglycinamide_formyltransferase": "#fb5746",
  "Pur_4_purL_phosphoribosylformylglycinamidine _synthase ": "#fb5746",
  "Pur_5_purM_Phosphoribosylformylglycinamidine_cyclo-ligase ": "#fb5746",
  "Pur_6_purK_phosphoribosylaminoimidazole_carboxylase": "#fb5746",
  "Pur_7_purE_5-(carboxyamino)imidazole_ribonucleotide_mutase ": "#fb5746",
  "Pur_8_purC_SAICAR_synthase": "#fb5746",
  "Pur_9_PurH\/PurP": "#fb5746",
  "Pyr_1_carbamoyl_P_synth": "#f1ab0c",
  "Pyr_10_CTP_synthase": "#f1ab0c",
  "Pyr_11_dCTP_deaminase": "#f1ab0c",
  "Pyr_12_dCMP_deaminase": "#f1ab0c",
  "Pyr_13_thymidylate_kinase": "#f1ab0c",
  "Pyr_14_ThyA_thymidylate_synthase": "#f1ab0c",
  "Pyr_2_aspartate_carbamoyltransferase": "#f1ab0c",
  "Pyr_3_dihydroorotase": "#f1ab0c",
  "Pyr_4_dihydroorotate_dehydrogenase": "#f1ab0c",
  "Pyr_5_orotate_phosphoribosyltransferase": "#f1ab0c",
  "Pyr_6_PRPP_synthase": "#f1ab0c",
  "Pyr_7_Orotidine-5-P_decarbox": "#f1ab0c",
  "Pyr_8_nucl_monophos_kinase": "#f1ab0c",
  "Pyr_9_nucl_diphosph_kinase": "#f1ab0c",
  "Flagella_related proteins": "#f0ff91",
  "Glycolysis": "#e3f514",
  "Entner-Doudoroff_pathway_two_key_enzymes_2011": "#f5540f",
  "Gluconeogenesis": "#e3f514",
  "Non-oxidative pentose phosphate pathway": "#f0f514",
  "Oxidative Pentose phosphate pathway": "#f0f514",
  "Purine metabolism": "#f55d5d",
  "Pyrimidine metabolism": "#f7c648",
  "Phenylalanyl-tRNA synthetase alpha subunit": "#EA175E",
  "Phenylalanyl-tRNA synthetase beta subunit": "#EA175E",
  "Histidyl-tRNA synthetase": "#84b7ba",
  "Leucyl-tRNA synthetase": "#84b7ba",
  "Valyl-tRNA synthetase": "#EA175E",
  "Cytochrome_c_Biogenesis": "#eda16b",
  "cell_surface_protein": "#b07979",
  "Glycogen_starch_synthase": "#8948b0",
  "Prolyl-tRNA synthetase ": "#84b7ba",
  "Glycogen _(starch) metabolism": "#8948b0",
  "Amylolytic Degradation": "#f7d49c",
  "Amylolytic Degradation Extracellular": "#f7d49c",
  "Alanyl-tRNA synthetase": "#84b7ba",
  "Arginyl-tRNA synthetase": "#84b7ba",
  "Glutaminyl-tRNA synthetase": "#84b7ba",
  "Isoleucyl--tRNA synthetase": "#84b7ba",
  "Methionyl-tRNA synthetase": "#EA175E",
  "Threonyl-tRNA synthetase": "#84b7ba",
  "Tryptophanyl-tRNA synthetase": "#84b7ba",
  "Seryl-tRNA synthetase ": "#84b7ba",
  "Lysyl-tRNA synthetase ": "#84b7ba",
  "Cysteinyl-tRNA synthetase ": "#84b7ba",
  "Glycyl-tRNA synthetase": "#EA175E",
  "Aspartyl-tRNA synthetase": "#84b7ba",
  "Tyrosyl-tRNA synthetase": "#84b7ba",
  "Asparaginyl-tRNA synthetase": "#84b7ba",
  "Gluconeogenesis_PEP_synthase": "#7c8bd6",
  "Gluconeogenesis_Fructose-1,6-bisphosphatase": "#7c8bd6",
  "Gluconeogenesis_Transketolase ": "#7c8bd6",
  "Urea_Cycle_carbamoyl-phosphate synthase": "#9eb5a0",
  "Urea_Cycle_Ornithine carbamoyltransferase ": "#9eb5a0",
  "Urea_Cycle_Argininosuccinate synthase": "#9eb5a0",
  "Urea_Cycle_Argininosuccinate lyase": "#9eb5a0",
  "Urea_Cycle_Ureohydrolase_Arginase": "#9eb5a0",
  "TCA_Aconitase": "#f53b3b",
  "TCA_Isocitrate DH": "#f53b3b",
  "TCA_Citrate Synthase": "#f53b3b",
  "TCA_Malate DH": "#f53b3b",
  "TCA_Succinate-CoA ligase": "#f53b3b",
  "TCA_Oxoglutarate DH\/OFOR": "#f53b3b",
  "Gluconeogenesis_Pep carboxykinase": "#7c8bd6",
  "TCA_Fumarate_hydratase": "#f53b3b",
  "Glycosyl_Transferase": "#f7d49c",
  "ABC transporter related protein": "#dceb1e",
  "Glycosyl_hydrolase": "#f7d49c",
  "Cytochrome_c_oxidase_subunit_I_Complex_IV": "#e69567",
  "Complex_II_Succinate_Dehydrogenase": "#e69567",
  "Complex_III": "#e69567",
  "Hydrogenase_maturation": "#779bbd",
  "ggKBase_malate_dehydrogenase_(oxaloacetate-decarboxylating)": "",
  "ggKBase_malate_dehydrogenase_TCA_pyruvate": "",
  "oxidative_stress": "",
  "Phage\/Virus": "",
  "Carbon_fixation_Reductive_TCA3_citrate_lyase": "#119c83",
  "Carbon_fixation_reductive_TCA1_fumarateReductase": "#119c83",
  "Carbon_fixation_reductive_TCA2_OFOR": "#119c83",
  "Carbon_fixation_calvin_cycle": "#119c83",
  "Hydrogenase_all_(not_maturation)": "#779bbd",
  "Carbon_fixation_Wood-Ljungdahl_P_6.3.4.3": "#119c83",
  "Peptidoglycan_biosynthesis": "#db914c",
  "Hydrogenase_NiFe": "#779bbd",
  "Dissimilatory_Sulfate_Reduction": "#5c7b82",
  "Methanogenesis_McrA": "#e487e6",
  "Methane_oxidation": "#e487e6",
  "Nitrogen_cycle_Putative_Nitrate_reductase": "#383233",
  "Nitrogen_cycle_Nitrite_reductase": "#c7edf2",
  "Nitrogen_Cycle_ammonia_monooxygenase": "#c7edf2",
  "Nitrogen_Cycle_hydroxylamine_oxidoreductase": "#131414",
  "Sulfur_oxidation_sox_pathway": "",
  "Blue_copper_protein": "#a8e3d5",
  "Cytochrome_c": "#a8e3d5",
  "Formate_Dehydrogenase": "#ffc2c2",
  "Beta_oxidation_Fatty_acids_3-hydroxyacyl-CoA dehydrogenase": "#bcebb0",
  "Beta_oxidation_Fatty_acids_enoyl_hydratase": "#baf5c3",
  "Beta_oxidation_Fatty_acids_Acyl-CoA_Dehydrogenase": "#a9deab",
  "Beta_oxidation_Fatty_acids_Acyl-CoA_synthetase": "#aef2b5",
  "electron_transfer_flavoprotein": "#a8e3d5",
  "RNF_complex": "#e69567",
  "Heterodisulfide_reductase_ABCD": "#779bbd",
  "Beta_oxidation_Fatty_acids_Acetyl-CoA_acetyltransferase": "#caf7c6",
  "AMP_salvage_Pathway_Rubisco": "#139a9c",
  "Complex_IV_cytochrome_bd_oxidase": "#e69567",
  "Lactate_Dehydrogenase": "#ffc2c2",
  "Complex_III_alternative_PETAB": "#e69567",
  "Hydrogenase_NiFe_catalytic subunit": "#779bbd",
  "TCA_Cycle": "",
  "TCA_Succinate_Dehydrogenase": "#f70f0f",
  "DMSO_Molybdopterin_oxidoreductase": "#2c92db",
  "Quinone_reductase_complex": "#e69567",
  "Sulfite_reductase": "#6dde93",
  "Ggkbase_polysaccharide_deacetylase": "#b93ff2",
  "Gluconeogenesis_four_key": "#17318a",
  "Ethylmalonyl-CoA_pathway_key_enzyme": "#e86b10",
  "Glycolysis_GW2011": "#64e380",
  "Trimethylamine N-oxide reductase_DMSO_GW2011 ": "#53b1f5",
  "Arsenate_reductase_DMSO_GW2011": "#53b1f5",
  "Arsenite_oxidase_DMSO_GW2011": "#53b1f5",
  "PfkB domain protein_Fructokinase-like": "#acc8f2",
  "deoxyribose phosphate aldolase_Putative_Fbpase": "#acc8f2",
  "PP_6-phosphogluconolactonase": "#dec8e6",
  "amino_acids_acetolactate_synthase": "#eddddd",
  "amino_acid_ketolacid_reductoisomerase": "#ebcccc",
  "amino_acid_phosphoglycerate_dehydrogenase ": "",
  "amino_acid_phosphoserine_aminotransferase": "",
  "amino_acid_phosphoserine_phosphatase ": "",
  "amino_acid_serine_hydroxymethyltransferase ": "",
  "amino_acid_threonine_aldolase": "",
  "amino_acid_Glutamate_aspartate_aminotransferase": "",
  "amino_acid_Glutamine_Glutamine_synthetase": "",
  "amino_acid_Isoleucine\/Valine": "",
  "amino_acid_Leucine": "",
  "amino_acid_Cysteine_t": "",
  "amino_acid_Glycine": "",
  "PP_Ribokinase": "#856491",
  "PP_ribose_phosphate_pyrophosphokinase": "#856491",
  "Phosphoenolpyruvate_carboxylase": "#27ce79",
  "16S rRNA": "#f9091f",
  "Pur_1_phosphoribosylamidotransferase": "#fb5746",
  "Pur_2_Phosphoribosylglycinamide_synthase": "#fb5746",
  "Pur_3_purN_purT": "#fb5746",
  "Pur_4_purL": "#fb5746",
  "Pur_5_purM": "#fb5746",
  "Pur_7_purE": "#fb5746",
  "Pur_6_purK": "#fb5746",
  "Pur_12_adenylosuccinate_lyase": "#fb5746",
  "Pur_13_IMP_dehydrogenase": "#fb5746",
  "Pur_14_GMP_synthase": "#fb5746",
  "Pur_15_xanthine_phosphoribosyltransferase": "#fb5746",
  "Pur_11_adenylosuccinate_synthase": "#fb5746",
  "Pur_9_formyltransferase": "#fb5746",
  "CCA-adding enzyme": "#EA175E",
  "DNA-directed RNA polymerase": "#EA175E",
  "DNA-directed RNA polymerase subunit N": "#EA175E",
  "Dimethyladenosine transferase": "#EA175E",
  "Diphthamide biosynthesis protein": "#EA175E",
  "Fibrillarin-like rRNA\/tRNA 2-O-methyltransferase": "#EA175E",
  "KH type 1 domain protein": "#EA175E",
  "Non-canonical purine NTP pyrophosphatase": "#EA175E",
  "PUA domain containing protein": "#EA175E",
  "Pre-mRNA processing ribonucleoprotein": "#EA175E",
  "Prolyl-tRNA synthetase": "#EA175E",
  "Protein pelota homolog": "#EA175E",
  "Ribosomal protein L10e": "#EA175E",
  "Ribosomal protein L13": "#EA175E",
  "Ribosomal protein L18e": "#EA175E",
  "Ribosomal protein L21e": "#EA175E",
  "Ribosomal protein L3": "#EA175E",
  "Ribosomal protein L7Ae\/L8e": "#EA175E",
  "Ribosomal protein S13": "#EA175E",
  "Ribosomal protein S15": "#EA175E",
  "Ribosomal protein S19e": "#EA175E",
  "Ribosomal protein S2": "#EA175E",
  "Ribosomal protein S28e": "#EA175E",
  "Ribosomal protein S3Ae": "#EA175E",
  "Ribosomal protein S6e": "#EA175E",
  "Ribosomal protein S7": "#EA175E",
  "Ribosomal protein S9": "#EA175E",
  "Ribosome maturation protein SDO1 homolog": "#EA175E",
  "Signal recognition particle 54 kDa protein": "#EA175E",
  "Transcription elongation factor Spt5": "#EA175E",
  "Translation initiation factor 5A": "#EA175E",
  "Translation initiation factor IF-2 subunit gamma": "#EA175E",
  "tRNA N6-adenosine threonylcarbamoyltransferase": "#EA175E",
  "All Cytochrome": "#a8e3d5"
};

var phyloColors = {
  "root" : "#ffffff",
  "Bacteria": "#5687d1",
  "Archaea": "#de783b",
  "Eukaryota": "#6ab975",
  "Viruses": "#785F43",
  "Metazoa": "#A113A1",
  "unknown": "#eeeeee",
  "Proteobacteria" : "#B7B180", 
  "Ascomycota" : "#22700F", 
  "Planctomycetes" : "#4DB6FF", 
  "Acidobacteria" : "#5EFFA1", 
  "Deinococcus-Thermus" : "#F6CAF2", 
  "Spirochaetes" : "#F36579", 
  "Verrucomicrobia" : "#B4FF00", 
  "Chloroflexi" : "#D15800", 
  "Firmicutes" : "#BBD181", 
  "Euryarchaeota" : "#FFFF0F", 
  "Apicomplexa" : "#227000", 
  "Bacteroidetes" : "#FDE4A5", 
  "Thermotogae" : "#6081FF", 
  "Crenarchaeota" : "#BFBF4F", 
  "Chytridiomycota" : "#227000", 
  "Aquificae" : "#A8FFDA", 
  "Dictyoglomi" : "#89AFFF", 
  "Actinobacteria" : "#2444FF", 
  "Thermodesulfobacteria" : "#7D2726", 
  "Cyanobacteria" : "#4FFF00", 
  "Nitrospirae" : "#ABBFE0", 
  "Fusobacteria" : "#B79EFF", 
  "Chlorobi" : "#3F9600", 
  "Chlorophyta" : "#227000", 
  "Ignavibacteria" : "#FFFF00", 
  "Deferribacteres" : "#F7A541", 
  "Synergistetes" : "#C9FFBA", 
  "Thaumarchaeota" : "#B8BF4F", 
  "Archaeon" : "#FFFF92", 
  "Chordata" : "#227000", 
  "Caldiserica" : "#4D0057", 
  "Chlamydiae" : "#F00000", 
  "Placozoa" : "#227000", 
  "Tenericutes" : "#000084", 
  "Arthropoda" : "#227000", 
  "Elusimicrobia" : "#7529FF", 
  "Chrysiogenetes" : "#000000", 
  "Streptophyta" : "#227000", 
  "Echinodermata" : "#227000", 
  "Gemmatimonadetes" : "#EA15D6", 
  "Basidiomycota" : "#227000", 
  "Nematoda" : "#227000", 
  "Fibrobacteres" : "#DBA9A8", 
  "Lentisphaerae" : "#227000", 
  "Bacillariophyta" : "#227000", 
  "Phaeophyceae" : "#227000", 
  "Poribacteria" : "#227000", 
  "Nanoarchaeota" : "#FEFF81", 
  "Cnidaria" : "#227000", 
  "Microsporidia" : "#227000", 
  "Korarchaeota" : "#E3EC5F", 
  "Mollusca" : "#227000", 
  "Porifera" : "#227000", 
  "Platyhelminthes" : "#227000", 
  "Glomeromycota" : "#227000", 
  "Euglenida" : "#227000", 
  "TM7" : "#6D6D6D", 
  "Caldithrix" : "#AEFF7D"
};
